trigger:
  - main

pool:
  vmImage: ubuntu-latest

steps:
  - checkout: self
    submodules: true
  - task: Bash@3
    displayName: NPM install
    inputs:
      targetType: 'inline'
      script: |
        cd $(System.DefaultWorkingDirectory)/inoffice && npm install

  - task: Bash@3
    displayName: NPM run build
    inputs:
      targetType: 'inline'
      script: |
        cd $(System.DefaultWorkingDirectory)/inoffice && npm run build

  - task: AzureStaticWebApp@0
    inputs:
      app_location: '/'
      api_location: ''
      output_location: './inoffice/build'
      skip_app_build: true
      azure_static_web_apps_api_token: $(deployment_token)
  