trigger:
  - feature/*
  - bug/*
  - story/*
  - main

pool:
  vmImage: ubuntu-latest
  
variables:
  artifactName: 'www'
  app_location: 'mydesk'

stages:


- stage: Build

  jobs:
  - job: build
    displayName: Build app
    steps:
    
    - script: npm install
      displayName: 'Install Dependencies'
      condition: ne(variables['Build.SourceBranch'], 'refs/heads/main')
      workingDirectory: '$(System.DefaultWorkingDirectory)/$(app_location)'
     
    - script: npm run build
      displayName: 'Build application'
      condition: ne(variables['Build.SourceBranch'], 'refs/heads/main')
      workingDirectory: '$(System.DefaultWorkingDirectory)/$(app_location)'
    
    - task: CopyFiles@2
      displayName: 'Copy Build Output'
      condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
      inputs:
          Contents: '$(app_location)/**'
          TargetFolder: '$(Build.ArtifactStagingDirectory)'               
    - task: PublishBuildArtifacts@1
      displayName: 'Publish to Azure Pipelines'
      condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
      inputs:
          PathtoPublish: $(Build.ArtifactStagingDirectory)
          ArtifactName: $(artifactName)
          

- stage: Dev
  displayName: Deploy to dev environment 
  dependsOn: Build
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))

  jobs:
    - deployment: deploy
      displayName: Deploy to dev
      environment: development
      variables:
      - group: mydesk-fe-dev
      strategy:
        runOnce:
          deploy:
            steps:

            - download: none
            - checkout: none

            - task: DownloadBuildArtifacts@1
              displayName: Download artifacts
              inputs:
                buildType: current
                downloadType: single
                artifactName: $(artifactName)
                downloadPath: $(System.ArtifactsDirectory)

            - task: AzureStaticWebApp@0
              displayName: Deploy to dev
              inputs:
                app_location: $(app_location)
                skip_app_build: false
                skip_api_build: false
                verbose: true
                azure_static_web_apps_api_token: $(AZURE_STATIC_WEB_APPS_API_TOKEN)
                deployment_environment: development
                workingDirectory: $(System.ArtifactsDirectory)/$(artifactName)
              env:
                REACT_APP_API_URL: $(REACT_APP_API_URL)
                REACT_APP_CLIENT_ID: $(REACT_APP_CLIENT_ID)
                REACT_APP_TENANT_ID: $(REACT_APP_TENANT_ID)
                REACT_APP_URL: $(REACT_APP_URL)
                REACT_APP_GOOGLE_CLIENT_ID: $(REACT_APP_GOOGLE_CLIENT_ID)


- stage: Production
  displayName: Deploy to production environment 
  dependsOn: Dev
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))

  jobs:
    - deployment: deploy
      displayName: Deploy to production
      environment: production
      variables:
      - group: mydesk-fe-production
      strategy:
        runOnce:
          deploy:
            steps:

            - download: none
            - checkout: none

            - task: DownloadBuildArtifacts@1
              displayName: Download artifacts
              inputs:
                buildType: current
                downloadType: single
                artifactName: $(artifactName)
                downloadPath: $(System.ArtifactsDirectory)

            - task: AzureStaticWebApp@0
              displayName: Deploy to production
              inputs:
                app_location: $(app_location)
                skip_app_build: false
                skip_api_build: false
                verbose: true
                azure_static_web_apps_api_token: $(AZURE_STATIC_WEB_APPS_API_TOKEN)
                workingDirectory: $(System.ArtifactsDirectory)/$(artifactName)
              env:
                REACT_APP_API_URL: $(REACT_APP_API_URL)
                REACT_APP_CLIENT_ID: $(REACT_APP_CLIENT_ID)
                REACT_APP_TENANT_ID: $(REACT_APP_TENANT_ID)
                REACT_APP_URL: $(REACT_APP_URL)
                REACT_APP_GOOGLE_CLIENT_ID: $(REACT_APP_GOOGLE_CLIENT_ID)

