trigger:
  - main

pool:
  vmImage: ubuntu-latest

steps:
  - checkout: self
    submodules: true

  - task: NodeTool@0 
    inputs:
      versionSpec: '16.14.0'

  - task: AzureStaticWebApp@0
    inputs:
      app_location: "inoffice"
      output_location: "build"
      azure_static_web_apps_api_token: $(deployment_token)