trigger:
  - main

pool:
  vmImage: ubuntu-latest

steps:
  - checkout: self
    submodules: true
  - task: Npm@1
    inputs:
      command: 'install'
      workingDir: './'
  
  - task: Npm@1
    inputs:
      command: 'custom'
      workingDir: './'
      customCommand: 'run build'
  
  - task: AzureStaticWebApp@0
    inputs:
      app_location: '/inoffice/src'
      api_location: ''
      output_location: '/inoffice/build'
      azure_static_web_apps_api_token: $(deployment_token)
  