export const allJobsList = [
  { id: 1, title: "Brand Marketing Manager" },
  { id: 2, title: "Business development Manager" },
  { id: 3, title: "Business Development Partner" },
  { id: 4, title: "CEO" },
  { id: 5, title: "CFO & Managing Partner" },
  { id: 6, title: "Chief People and Talent Officer" },
  { id: 7, title: "CHRO" },
  { id: 8, title: "CIO" },
  { id: 9, title: "Co-Founder" },
  { id: 10, title: "Content Creator and Editor" },
  { id: 11, title: "Content Uploader" },
  { id: 12, title: "CPO" },
  { id: 13, title: "CRM Engineer" },
  { id: 14, title: "CTO" },
  { id: 15, title: "CXO" },
  { id: 16, title: "Data Analyst" },
  { id: 17, title: "Data Architect" },
  { id: 18, title: "Digital Marketing Specialist" },
  { id: 19, title: "Employer Branding Marketing Specialist" },
  { id: 20, title: "Finance and Accounting Specialist" },
  { id: 21, title: "Full-stack Software Engineer" },
  { id: 22, title: "General Manager" },
  { id: 23, title: "Graphic Designer" },
  { id: 24, title: "Head of Technology" },
  { id: 25, title: "Intermediate Back-end Engineer" },
  { id: 26, title: "Intermediate Business Analyst" },
  { id: 27, title: "Intermediate Data Analyst" },
  { id: 28, title: "Intermediate Database Administrator" },
  { id: 29, title: "Intermediate DevOps Engineer" },
  { id: 30, title: "Intermediate Front-end Engineer" },
  { id: 31, title: "Intermediate Full Stack Engineer" },
  { id: 32, title: "Intermediate Java Engineer" },
  { id: 33, title: "Intermediate Project Manager" },
  { id: 34, title: "Intermediate Quality Assurance Engineer" },
  { id: 35, title: "Intermediate Recruiter" },
  { id: 36, title: "Intermediate System Administrator-DevOps" },
  { id: 37, title: "Intermediate UX UI Designer" },
  { id: 38, title: "Intern" },
  { id: 39, title: "Junior Back-end Engineer" },
  { id: 40, title: "Junior Business Analyst" },
  { id: 41, title: "Junior Database Administrator" },
  { id: 42, title: "Junior DevOps" },
  { id: 43, title: "Junior Front-end Engineer" },
  { id: 44, title: "Junior Full-stack Engineer" },
  { id: 45, title: "Junior Python ML Engineer" },
  { id: 46, title: "Junior Quality Assurance Engineer" },
  { id: 47, title: "Junior Recruiter" },
  { id: 48, title: "Junior System Administrator" },
  { id: 49, title: "Junior Talent Acquisition" },
  { id: 50, title: "Lead Database Administrator" },
  { id: 51, title: "Lead DevOps Engineer" },
  { id: 52, title: "Lead Quality Assurance Engineer" },
  { id: 53, title: "Lead System Administrator - DevOps" },
  { id: 54, title: "Legal Advisor" },
  { id: 55, title: "Legal Executive Advisor" },
  { id: 56, title: "Marketing" },
  { id: 57, title: "Marketing Coordinator" },
  { id: 58, title: "Marketing Manager" },
  { id: 59, title: "Mid Project Manager" },
  { id: 60, title: "Office Growth Manager" },
  { id: 61, title: "Office Manager" },
  { id: 62, title: "People Development Coach and Strategist" },
  { id: 63, title: "People Engagement Specialist" },
  { id: 64, title: "President & Co-Founder" },
  { id: 65, title: "Principal Quality Assurance Engineer" },
  { id: 66, title: "Principal Software Architect" },
  { id: 67, title: "Principal Software Engineer" },
  { id: 68, title: "Project Lead" },
  { id: 69, title: "Prospecting Manager" },
  { id: 70, title: "Prospecting Project Manager" },
  { id: 71, title: "Recruitment and Employee Engagement Specialist" },
  { id: 72, title: "Sales" },
  { id: 73, title: "Sales and Media Support Specialist" },
  { id: 74, title: "Senior Back-end Engineer" },
  { id: 75, title: "Senior Business Analyst" },
  { id: 76, title: "Senior Database Administrator" },
  { id: 77, title: "Senior DevOps Engineer" },
  { id: 78, title: "Senior Front-end Engineer" },
  { id: 79, title: "Senior Full Stack Engineer" },
  { id: 80, title: "Senior Microsoft Dynamics Engineer" },
  { id: 81, title: "Senior Mobile" },
  { id: 82, title: "Senior People Administration Expert" },
  { id: 83, title: "Senior Project Manager" },
  { id: 84, title: "Senior Quality Assurance Engineer" },
  { id: 85, title: "Senior Recruiter" },
  { id: 86, title: "Senior Security Officer" },
  { id: 87, title: "Senior Software Engineer" },
  { id: 88, title: "Senior System Administrator-DevOps" },
  { id: 89, title: "Strategic Development Specialist" },
  { id: 90, title: "SysOps/DevOps Engineer" },
  { id: 91, title: "Talent Acquisition Lead" },
  { id: 92, title: "Talent Acquisition Specialist" },
  { id: 93, title: "Technical Lead" },
];
